version: '3.4'

services:
  database:
    image: postgres:alpine
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=project-mgmt
    ports:
      - '5432:5432'
    restart: always

  api:
    build: api
    volumes:
      - ./api:/index
    ports:
      - 3001:3001
    depends_on:
      - "database"

  # freejeffrootconfig:
  #   build: root-config
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - "database"

  # freejeffmainpage:
  #   build: main-page
  #   ports:
  #     - 8001:8001
  #   # depends_on:
  #     # - "database"

  # freejeffnavbar:
  #   build: navbar
  #   ports:
  #   - 8002:8002

volumes:
  project-mgt: {}
