version: '3.4'

services:
  database:
    image: postgres:alpine
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=project-mgmt
    ports:
      - '5432:5432'
    restart: always

  api:
    build: api
    volumes:
      - ./api:/index
    ports:
      - 3001:3001
    depends_on:
      - "database"
  auth-api:
    build: user_auth_api2
    volumes:
      - ./user_auth_api2:/src/app
    ports:
      - 8080:8080
    depends_on:
      - "database"
volumes:
  project-mgt: {}
