version: '3.4'

services:
  freejeffrootconfig:
    image: freejeffrootconfig
    build:
      context: root-config
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8000:8000
      - 8229:8229
    command: ["node", "--inspect=0.0.0.0:8229", "index.js"]
